HELLO_WORLD:=Hello world!

target: prerequisite
	echo "Making target from prerequisite"
	cp prerequisite target

prerequisite:
	echo "Making prerequisite"
	echo "I am a prerequisite. $(HELLO_WORLD)" > prerequisite
