.PHONY: clean
clean:
	rm alphabet-*.txt


ALPABET_ONE_BY_ONE:=alphabet-one-by-one.txt

.PHONY: a b c d e f g h i j k l m n o p q r s t u v w x y z
a:
	echo "a" >> $(ALPABET_ONE_BY_ONE)
b: a
	echo "b" >> $(ALPABET_ONE_BY_ONE)
c: b
	echo "c" >> $(ALPABET_ONE_BY_ONE)
d: c
	echo "d" >> $(ALPABET_ONE_BY_ONE)
e: d
	echo "e" >> $(ALPABET_ONE_BY_ONE)
f: e
	echo "f" >> $(ALPABET_ONE_BY_ONE)
g: f
	echo "g" >> $(ALPABET_ONE_BY_ONE)
h: g
	echo "h" >> $(ALPABET_ONE_BY_ONE)
i: h
	echo "i" >> $(ALPABET_ONE_BY_ONE)
j: i
	echo "j" >> $(ALPABET_ONE_BY_ONE)
k: j
	echo "k" >> $(ALPABET_ONE_BY_ONE)
l: k
	echo "l" >> $(ALPABET_ONE_BY_ONE)
m: l
	echo "m" >> $(ALPABET_ONE_BY_ONE)
n: m
	echo "n" >> $(ALPABET_ONE_BY_ONE)
o: n
	echo "o" >> $(ALPABET_ONE_BY_ONE)
p: o
	echo "p" >> $(ALPABET_ONE_BY_ONE)
q: p
	echo "q" >> $(ALPABET_ONE_BY_ONE)
r: q
	echo "r" >> $(ALPABET_ONE_BY_ONE)
s: r
	echo "s" >> $(ALPABET_ONE_BY_ONE)
t: s
	echo "t" >> $(ALPABET_ONE_BY_ONE)
u: t
	echo "u" >> $(ALPABET_ONE_BY_ONE)
v: u
	echo "v" >> $(ALPABET_ONE_BY_ONE)
w: v
	echo "w" >> $(ALPABET_ONE_BY_ONE)
x: w
	echo "x" >> $(ALPABET_ONE_BY_ONE)
y: x
	echo "y" >> $(ALPABET_ONE_BY_ONE)
z: y
	echo "z" >> $(ALPABET_ONE_BY_ONE)

$(ALPABET_ONE_BY_ONE): a b c d e f g h i j k l m n o p q r s t u v w x y z
